### PR TITLE
add-symbol-name-for-ios

### PR DESCRIPTION
**Pull request by nicolasdevienne**

### CODE REVIEW

**Comment by nicolasdevienne** [comment]
Hi @mouselangelo! Can you check this PR please?

**Comment by nicolasdevienne** [comment]
> Hi @mouselangelo! Can you check this PR please?

Hi @mouselangelo! Is it possible to review and merge this PR please? Thx!!

**Comment by nicolasdevienne** [comment]
> > Hi @mouselangelo! Can you check this PR please?
> 
> Hi @mouselangelo! Is it possible to review and merge this PR please? Thx!!

@mouselangelo :)

**Review by mouselangelo — APPROVED** [review]
Thanks for adding this 🙏

**Comment by mouselangelo** [comment]
Apologies for not seeing your messages earlier @nicolasdevienne

**Comment by nicolasdevienne** [comment]
> Apologies for not seeing your messages earlier @nicolasdevienne

No problem, thx! Can you merge PR and publish new release?

**Comment by nicolasdevienne** [comment]
> > Apologies for not seeing your messages earlier @nicolasdevienne
> 
> No problem, thx! Can you merge PR and publish new release?

@mouselangelo :)

**Pull request closed without merging**
